language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
after_script: "npm install coveralls@2.11.1 && cat ./coverage/PhantomJS*/lcov.info | coveralls"